version: "3.3"
services:
  whisper_asr:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: whisper_asr:latest
    container_name: whisper_asr
    hostname: whisper_asr
    ports:
      - "8503:8503"
      # - "7860:7860"
    networks:
      - my-network
    volumes:
      - ./audios:/app/audios
      - ./downloads:/app/downloads
      - ./transcripts:/app/transcripts
      - ./transcripts_gradio:/app/transcripts_gradio
    restart: unless-stopped
networks:
  my-network:
    driver: bridge